#!/bin/bash

# Function to display script usage information
display_help() {
    echo "Usage: $0"
    echo "  This script copies all text files from the solution repo and backs them up in a private repository." 
}

# Check if the user requested help
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    display_help
    exit 0
fi

# Loop through text files and copy them
find "$AOC_SOLUTION_REPO" -type f -name "*.txt" -not -path "*/node_modules/*" | while IFS= read -r file; do
    destination_path="$AOC_INPUT_REPO${file#$AOC_SOLUTION_REPO}"
    mkdir -p "$(dirname "$destination_path")"
    cp "$file" "$destination_path"
done
